#ifndef CUTCOL_H
#define CUTCOL_H
#include <tesseract/baseapi.h>
#include <leptonica/allheaders.h>
using namespace std;
using namespace cv;

int Max(int a, int b);
int Min(int a, int b);
int Middle(vector<int> elem, int n);
Mat norm(const Mat& src);
Mat inhance(Mat src, float gamma);
vector<int> getWrapandCutpos(Mat src1);
vector<int*> splitBySingleStroke(vector<int*> combined, vector<vector<int*>> singleStrokes);
vector<vector<int*>> detectSingleStroke(Mat binaryLineImg, vector<int*> potentialPT, int heightThreshold, int widthThreshold);
vector<int*> detectPotentialPT(vector<int*> combinedCC, int LH, float thetah1, float thetah2);
int estimateComponentsMean(vector<int*> combinedCC);
void adjustCombinedComponent(vector<int*> cc);
vector<int*> combineOverlapComponents(vector<int*> cc);
bool coordinateCmp(int *p, int *q);
bool contoursizeCmp(int *p, int *q);
bool xCmp(Point p1, Point p2);
bool yCmp(Point p1, Point p2);
bool widthCmp(int p, int q);
bool contourlencmp(vector<Point> c1, vector<Point> c2);
vector<int*> CCPoints2Coordinates(vector<vector<Point>> cc);
vector<int*> CCPoints2Coordinates1(vector<vector<Point>> cc);
vector<int*> combinecoord(vector<int*> coordinates);
vector<int*> combinecoord1(vector<int*> coordinates, bool rmb);
vector<int*> combinecoord2(vector<int*> coordinates);
vector<int*> combinecoord_for_realaccount(vector<int*> coordinates);
vector<int*> combinecoord_for_five(const vector<int*> &coordinates, const vector<vector<Point>> &contours);
vector<int*> combinecoord_for_five_h(const vector<int*> &coordinates, const vector<vector<Point>> &contours);
vector<int> combinecoordforPrintNum(vector<int*> coordinates, bool rmb);
vector<int*> combinecoordtofilterPrint(vector<int*> coordinates);
void drawContours(Mat img, vector<vector<Point>>contours);
void removeShortContours(vector<vector<Point>>& contours, int cmin, int cmax);
vector<Point> getMaxContours(vector<vector<Point>> contours);
vector<vector<int>> contoursRows(vector<Point> contour, int y1, int y2);
int otsu2(IplImage *image);
void deleteLines(Mat binLine, int lineLength);
void RemoveSmallRegion(Mat& Src, Mat& Dst, int AreaLimit, int CheckMode, int NeihborMode);
vector<Vec4i> drawLinesforPic(Mat gray, int len, int dis);
vector<Vec4i> drawLinesforPic1(Mat gray, int len, int dis);
Mat splitTored(Mat src);
void setPathOfexe(char *savedir);
vector<int> getcutPoint(vector<int*> split, Mat fgImg);
Mat CutfromLeftandRight(Mat src);
void thinimage(Mat &srcimage);
void savePicture(vector<int> fg, string filename, char* Savedir, Mat fgImg);
void saverecPic(vector<int*> split, string filename, char* Savedir, Mat fgImg);
void saverec(vector<int*> split, string filename, char* Savedir, Mat fgImg);
void quickSort(int s[], int l, int r);
Mat matrixWiseMulti(Mat &m1, Mat &m2);
Mat ACE(Mat &src, int C = 3, int n = 3, float MaxCG = 7.5);
Mat myACE(Mat &src, int n = 7, float MaxCG = 7.5);
int FindByTwo(int *nums, int number);
void getAllFiles(string path, vector<string>& files);
vector<int> getCutfromleftandright(Mat src);
vector<int> getCutfromupanddown(Mat src);
int getCutfromup(Mat src);
int getFirstpos(Mat src);
bool firstwhite(Mat src);
vector<int> getcutpos(IplImage *img, int shrink);
int traverseCutPoint(Mat src);
vector<int*> combinecombined(vector<int*>, Mat src);
vector<int*> morecut(Mat src);
vector<int> maptolookcut(IplImage *img);
cv::Mat thinImage(const cv::Mat & src, const int maxIterations = -1);
void filterOver(Mat thinSrc);
vector<Point> getPoints(Mat thinSrc, int raudis, int thresholdMax, int thresholdMin);
Mat getthinImage(Mat src);
bool SingleCut(Mat src, int pos);
int MapsumtoCut(Mat img, int* range);
int MapsumtoCuty(Mat img);
int Crest(Mat src);
vector<vector<Point>> removeShortContoursfornumber(vector<vector<Point>>& contours, int rows);
vector<vector<Point>> removeShortContoursfornumber1(vector<vector<Point>>& contours, int rows);
void remove_vertical_line_between_number(vector<vector<Point>>& contours, float rotio);
vector<vector<Point>> removeShortContoursforCompany(vector<vector<Point>>& contours, int rows);
int* getFirstPrintPos(Mat src);
void MyGammaCorrection(Mat& src, Mat& dst, float fGamma);
Mat getFFTresultImg(Mat& completeI, CvSize srcSize);
Mat FFT(Mat& src_gray);
Mat clcGLPFMat(Mat& mat, int D0);
Mat mask(Mat& plane, float a, float b);
Mat CutNoiseforCompanyName(Mat img);
Mat getbilateralFilterMat(Mat src, int a, double b, double c);
vector<int*> getneighbor(Mat src, int x, int y);
bool existin_passed_points(int* point, vector<int*> cutpath);
int* gethighestpoint_x(vector<int*> coord, int ly, int ry);
Mat erase_for_five(Mat src, Mat &five_line);
Mat cut_margin_for_pic(Mat src);
void map_to_remove(Mat img, int* sum);
void map_to_locate(Mat img, int* sum);
bool haveNoCircle(Mat src);
#endif // CUTCOL_H

